### ISSUE TITLE
[Hexo 使用问题汇报] 无法部署网站

### ISSUE THREAD

**Issue by YUANbeautiful7** [EasyHexo/Easy-Hexo#109]
- 问题简介（*）无法通过hexo d将修改的hexo上传到布置的git上

- Hexo 版本（*）
hexo 3.8.0

- 使用的主题以及版本（*）
next pisces

- 预想结果（*）修改博客后，上传到github上

- 实际结果（*）本地的可以查看，github.io上不行

- 您的网站
YUANbeautif7.github.io

- 其他信息

**Comment by YUANbeautiful7** [comment]
# Deployment
## Docs: https://hexo.io/docs/deployment.html

**Comment by ChungZH** [comment]
> 
> # Deployment
> ## Docs: https://hexo.io/docs/deployment.html

发下面的那些选项 :joy:

**Comment by YUANbeautiful7** [comment]
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:YUANbeautiful7/YUANbeautiful7.github.io.git
  branch: master

**Comment by ChungZH** [comment]
用代码块语法。。

**Comment by YUANbeautiful7** [comment]
...
yml
Docs: https://hexo.io/docs/deployment.html
deploy:
type: git
repository: git@github.com:YUANbeautiful7/YUANbeautiful7.github.io.git
branch: master

**Comment by YUANbeautiful7** [comment]
'''yml
Docs: https://hexo.io/docs/deployment.html
deploy:
type: git
repository: git@github.com:YUANbeautiful7/YUANbeautiful7.github.io.git
branch: master'''

**Comment by JunzhouLiu** [comment]
```yml
deploy:
  type: git
  repo:
     github: https://github.com/YUANbeautiful7/YUANbeautiful7.github.io.git
  branch: master
  message:
```
like this

![image](https://user-images.githubusercontent.com/17582066/52049099-da9c4d80-2587-11e9-81e4-e414500c8ec2.png)

**Comment by JunzhouLiu** [comment]
@YUANbeautiful7 You need to follow the YML grammar rules !  Reference: [YAML 语法简介](https://easyhexo.github.io/Easy-Hexo/5-Add/5-2-yaml.html)

**Comment by YUANbeautiful7** [comment]
thanks
