### ISSUE TITLE
希望增加 hexo-theme-matery 主题的内容

### ISSUE THREAD

**Issue by blinkfox** [EasyHexo/Easy-Hexo#153]
你好，希望增加下[hexo-theme-matery](https://github.com/blinkfox/hexo-theme-matery)主题的内容，主要内容可以直接使用我主题的[中文说明](https://github.com/blinkfox/hexo-theme-matery/blob/develop/README_CN.md)即可。

**Comment by ChungZH** [comment]
十分感谢您的支持 😘！我们会尽快整理并添加有关内容的。

**Comment by blinkfox** [comment]
嗯，谢谢！

**Comment by ChungZH** [comment]
#156 已合并，如果还有问题可以回复下。没问题的话我就 close 了哈~

**Comment by blinkfox** [comment]
行，可以了，谢谢！
