### ISSUE TITLE
hexo-blog-encrypt - 加密单篇博客的插件

### ISSUE THREAD

**Issue by g-zhima** [EasyHexo/Easy-Hexo#159]
[hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt)一个可以加密单篇博客的插件，有的人大概有这方面的需求。

**Comment by ChungZH** [comment]
收到，感觉挺有用的~

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
如果时间不紧的话，我可以帮忙写一篇，恰好我也装了这个插件。
