### ISSUE TITLE
有关「利用 Hexo + CI 持续集成」部分内容的撰写

### ISSUE THREAD

**Issue by spencerwoo98** [EasyHexo/Easy-Hexo#17]
不知道大佬有没有计划介绍 Hexo + Travis CI 部署到 GitHub Pages 自动化流程这部分内容的打算，这方面我最近探索了一下感觉很好，如有需要可以供稿～

**Comment by ChungZH** [comment]
感谢大佬关心，哈哈~
我们这个项目正准备使用 CI，如能提供这方面的内容，我们将不胜感激！
Thanks 😘 ~

**Comment by MoshiYeap** [comment]
>           不知道大佬有没有计划介绍 Hexo + Travis CI 部署到 GitHub Pages 自动化流程这部分内容的打算，这方面我最近探索了一下感觉很好，如有需要可以供稿～

非常欢迎您的加入！！！:heart:

**Comment by ChungZH** [comment]
@spencerwoo98 http://gitter.im/easy-hexo-developer/
