### ISSUE TITLE
文档问题：文档中 YAML语法 链接404

### ISSUE THREAD

**Issue by AlliotTech** [EasyHexo/Easy-Hexo#170]
[这里](https://github.com/EasyHexo/Easy-Hexo/tree/master/docs/3-Plugins-use-and-config/3-3-hexo-helper-live2d#配置) 中的 链接： https://github.com/EasyHexo/Easy-Hexo/blob/master/5-Add/5-2-yaml.html 出现404了

**Comment by ChungZH** [comment]
收到😂正在修复

**Comment by MonoLogueChi** [comment]
@ChungZH 这个不是Bug，不需要修复，这是网站的绝对路径
