### ISSUE TITLE
hexo-theme-sakura文档

### ISSUE THREAD

**Issue by leeyiding** [EasyHexo/Easy-Hexo#187]
请求完善hexo-theme-sakura文档，[中文文档地址](https://github.com/honjun/hexo-theme-sakura/blob/master/README-zh_cn.md)

**Comment by ChungZH** [comment]
好的，有空看看~~逃~~

**Comment by ChungZH** [comment]
https://github.com/xbclub/Hexo-theme-sakura 这个好像更好 :thinking:

**Comment by leeyiding** [comment]
> https://github.com/xbclub/Hexo-theme-sakura 这个好像更好

这个是基于hexo-sakura二次开发的，用户数量肯定没有原版的多

**Comment by ChungZH** [comment]
:smile: 用户数量问题不大 好用就行
