### ISSUE TITLE
Hexo-theme-icarus 内容撰写

### ISSUE THREAD

**Issue by ChungZH** [EasyHexo/Easy-Hexo#77]
如有熟悉该主题的大佬，请领取该任务。
~~任务奖励：风太大我听不见！~~
[Hexo-theme-icarus](https://github.com/ppoffice/hexo-theme-icarus)

**Comment by ChungZH** [comment]
@Susreal 现在 `icarus` 的文档应该完成了？如果完成，我将 close 本 issue :smile_cat:

**Comment by Susreal** [comment]
check了一下发现有两个文章链接要改，又提了一个pull request，之后就算完成啦！

**Comment by ChungZH** [comment]
好的，完成 :tada:！
