### ISSUE TITLE
Hexo-theme-phantom 内容撰写

### ISSUE THREAD

**Issue by ChungZH** [EasyHexo/Easy-Hexo#79]
如有熟悉该主题的大佬，请速速领取任务。
~~任务奖励：风太大我听不见！~~
[Hexo-theme-phantom](https://github.com/klugjo/hexo-theme-phantom)
当然英文好的也可以翻译。[官方文档地址](https://github.com/klugjo/hexo-theme-phantom/blob/master/README.md)

**Comment by GatesMa** [comment]
我写(翻译)把

**Comment by ChungZH** [comment]
> 我写(翻译)把

好的，大佬加油
