### ISSUE TITLE
[好消息🎉🎉🎉]大家可以在这里提出你在使用 Hexo 的过程中遇到的问题啦

### ISSUE THREAD

**Issue by ChungZH** [EasyHexo/Easy-Hexo#87]
# 性感 EasyHexo，在线回答有关 Hexo 使用的问题！！！

大家可以~~为所欲为地~~在 Easy-Hexo 项目的 issue 区提出你使用 Hexo 时遇到问题，我们会尽量解答。

提出方法：点击[这儿](https://github.com/EasyHexo/Easy-Hexo/issues/new?assignees=&labels=Hexo+%E4%BD%BF%E7%94%A8%E9%97%AE%E9%A2%98&template=hexo-------.md&title=%5BHexo+%E4%BD%BF%E7%94%A8%E9%97%AE%E9%A2%98%E6%B1%87%E6%8A%A5%5D+%E4%BD%A0%E7%9A%84%E9%97%AE%E9%A2%98)，填写问题即可。

谢谢大家！

------

附成功样例：

- #109 无法部署网站
- #88 Valine 设置语言为英文

**Comment by penghubingzhou** [comment]
求教如何更换美观字体

**Comment by Molunerfinn** [comment]
希望提供`hexo-theme-melody`的使用与配置章节:smile:

**Comment by ChungZH** [comment]
收到，谢谢！
