### ISSUE TITLE
[Hexo 使用问题汇报] localhost:4000 无法打开

### ISSUE THREAD

**Issue by bree2y** [EasyHexo/Easy-Hexo#90]
- 问题简介（*修改主题的时候，不知道改了哪里使得localhost：4000本地网页无法打开，而通过***.github.io可进入）

- Hexo 版本（3.7.1*）

- 使用的主题以及版本（clexy*）

- 预想结果（
![image](https://user-images.githubusercontent.com/43675883/50668709-c18d9480-0ffb-11e9-984d-caf908731590.png)
*）

- 实际结果（
![image](https://user-images.githubusercontent.com/43675883/50668718-d0744700-0ffb-11e9-8531-90ba44bcc326.png)    
![image](https://user-images.githubusercontent.com/43675883/50668722-dec26300-0ffb-11e9-9ed4-6dc41fa5a642.png)

*）

- 您的网站https://bree2y.github.io/

- 其他信息

**Comment by ChungZH** [comment]
收到，正在查看。谢谢！

**Comment by MoshiYeap** [comment]
是hexo g后无法查看localhost4000？ 
可以尝试 -p, --port 命令重设端口

**Comment by bree2y** [comment]
> 可以用Chrome，Firefox浏览器试试 😃

不行

**Comment by bree2y** [comment]
> 是hexo g后无法查看localhost4000？
> 可以尝试-p， - port命令重设端口

之前重设过端口5000，还是不行

**Comment by Mitscherlich** [comment]
`hexo g` 是 `hexo generate` 命令的缩写，用于将博客静态化编译到 `<root>/public` 目录下，并不提供 `hexo-server` 服务端的功能；想要查看编译好的静态文件，可以通过 `hexo s -s [-p port]` 命令，或者使用 `serve` 工具：

```bash
$ npm i -g serve # 或者 yarn global add serve
$ serve public -p 4000
```

**Comment by ChungZH** [comment]
@bree2y 怎么样了？

**Comment by ChungZH** [comment]
@bree2y 可以了吗？
